from pydantic import BaseModel, EmailStr, Field, ConfigDict
from typing import Optional, List, Union
from datetime import datetime, date

# Import attendance schemas
from .attendance import (
    BranchResponse,
    ProgramResponse,
    GradeResponse,
    GradeTypeResponse,
    ShiftResponse,
    StudentAttendanceResponse,
    ClassInfoResponse,
    RecordAttendanceRequest,
    RecordAttendanceResponse,
)
from .news import NewsCreate, NewsUpdate, NewsResponse

class RoleResponse(BaseModel):
    id: int
    role_name: str
    
    model_config = ConfigDict(from_attributes=True)
    
from .academic_program import (
    AcademicProgramBase, AcademicProgramCreate, AcademicProgramUpdate, AcademicProgram
)
from .partner import (
    PartnerBase, PartnerCreate, PartnerUpdate, PartnerResponse
)
from .school_overview import (
    SchoolOverviewBase, SchoolOverviewCreate, SchoolOverviewUpdate, SchoolOverviewResponse
)
from .school_event import (
    SchoolEventBase, SchoolEventCreate, SchoolEventUpdate, SchoolEventResponse
)

# User Schemas
class UserBase(BaseModel):
    username: str
    uniqueId: Optional[str] = None  # Generated by backend
    kName: str  # Required field
    eName: str  # Required field
    height: float  # Required field
    gender: str  # Required field
    dob: date  # Required field
    nationality: str  # Required field
    religion: str  # Required field
    province: str  # Required field
    district: str  # Required field
    commune: str  # Required field
    education: str  # Required field
    workplace: int  # Required field
    status: int  # Required field
    role: int  # Required field
    isForeigner: int  # Required field
    email: Optional[str] = None
    phone: Optional[str] = None
    village: Optional[str] = None
    telegramId: Optional[str] = None
    pProvince: Optional[str] = None
    pDistrict: Optional[str] = None
    pCommune: Optional[str] = None
    pVillage: Optional[str] = None
    identityNumber: Optional[str] = None
    identityRegDate: Optional[date] = None
    identityEndDate: Optional[date] = None
    identityRegPlace: Optional[str] = None
    fatherName: Optional[str] = None
    motherName: Optional[str] = None
    departmentId: Optional[int] = None
    positionId: Optional[int] = None
    startWork: Optional[str] = None
    endWork: Optional[str] = None
    
    # Banking Information
    bankAccountNumber: Optional[str] = None
    bankAccountName: Optional[str] = None
    bankName: Optional[str] = None
    
    # Payroll Information
    baseSalary: Optional[float] = None
    
    # Identification & Social Security
    nssfNumber: Optional[str] = None
    isNssf: Optional[int] = 0
    isResident: Optional[int] = 1
    
    # Family Status
    hasSpouse: Optional[int] = 0
    numberOfDependents: Optional[int] = 0

class UserCreate(UserBase):
    password: str
    image: Optional[bytes] = None  # Binary image data (not used in registration; avatar handled separately)
    signature: Optional[bytes] = None  # Binary signature data

class UserResponse(UserBase):
    id: int
    image: Optional[bytes] = None  # For binary data
    signature: Optional[bytes] = None  # For binary data
    created_at: datetime
    updated_at: Optional[datetime] = None
    allowed_branches: Optional[List[int]] = None  # List of branch IDs user is authorized for

    model_config = ConfigDict(from_attributes=True)


class StaffRegisterResponse(UserResponse):
    """Registered staff profile plus the limited pending-session token."""

    access_token: str
    token_type: str = "bearer"
    pending_approval: bool = True

class UserMeResponse(BaseModel):
    """Simplified user response for /auth/me endpoint"""
    id: int
    username: str
    email: Optional[str] = None
    role: int
    status: int
    eName: Optional[str] = None
    kName: Optional[str] = None
    phone: Optional[str] = None
    workplace: Optional[int] = None  # Primary workplace/branch
    workplace_id: Optional[int] = None  # Alias for workplace
    branch_id: Optional[int] = None  # Alias for workplace
    allowed_branches: Optional[List[int]] = None  # List of authorized branch IDs
    allowedBranches: Optional[List[int]] = None  # CamelCase alias for Flutter
    created_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)

class UserLogin(BaseModel):
    username: str
    password: str

class UserUpdate(BaseModel):
    # All fields are optional for updates
    username: Optional[str] = None
    password: Optional[str] = None # Added password field
    old_password: Optional[str] = None # For password change verification
    uniqueId: Optional[str] = None
    kName: Optional[str] = None
    eName: Optional[str] = None
    height: Optional[float] = None
    gender: Optional[str] = None
    dob: Optional[date] = None
    nationality: Optional[str] = None
    religion: Optional[str] = None
    province: Optional[str] = None
    district: Optional[str] = None
    commune: Optional[str] = None
    education: Optional[str] = None
    workplace: Optional[int] = None
    status: Optional[int] = None
    role: Optional[int] = None
    isForeigner: Optional[int] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    village: Optional[str] = None
    telegramId: Optional[str] = None
    pProvince: Optional[str] = None
    pDistrict: Optional[str] = None
    pCommune: Optional[str] = None
    pVillage: Optional[str] = None
    identityNumber: Optional[str] = None
    identityRegDate: Optional[date] = None
    identityEndDate: Optional[date] = None
    identityRegPlace: Optional[str] = None
    fatherName: Optional[str] = None
    motherName: Optional[str] = None
    fatherPhone: Optional[str] = None
    motherPhone: Optional[str] = None
    fatherJob: Optional[str] = None
    motherJob: Optional[str] = None
    pEmail: Optional[str] = None
    pTelegramId: Optional[str] = None
    gName: Optional[str] = None
    gPhone: Optional[str] = None
    gIsThe: Optional[str] = None
    gHome: Optional[str] = None
    gStreet: Optional[str] = None
    gGroup: Optional[str] = None
    gProvince: Optional[str] = None
    gDistrict: Optional[str] = None
    gCommune: Optional[str] = None
    gVillage: Optional[str] = None
    departmentId: Optional[int] = None
    positionId: Optional[int] = None
    startWork: Optional[str] = None
    endWork: Optional[str] = None
    image: Optional[str] = None  # Base64-encoded profile image (for parent/teacher update)
    signature: Optional[bytes] = None

class Token(BaseModel):
    access_token: str
    refresh_token: Optional[str] = None
    token_type: str

# Role-based Login Schemas
class RoleBasedLogin(BaseModel):
    username: str
    password: str
    role: str  # "teacher", "student", "parent"

class StudentLoginResponse(BaseModel):
    """Response for student login"""
    id: int
    username: str
    studentid: Optional[str] = None
    kName: str
    eName: str
    gender: str
    dob: date
    academic: str
    branch: str
    status: int
    role: str = "student"
    
    model_config = ConfigDict(from_attributes=True)

class ParentLoginResponse(BaseModel):
    """Response for parent login"""
    id: int
    username: str
    uniqueid: str
    fatherName: str
    motherName: str
    fatherPhone: str
    motherPhone: Optional[str] = None
    role: str = "parent"
    
    model_config = ConfigDict(from_attributes=True)

class TeacherLoginResponse(BaseModel):
    """Response for teacher login (using existing UserMeResponse)"""
    id: int
    username: str
    email: Optional[str] = None
    role: int
    status: int
    eName: Optional[str] = None
    kName: Optional[str] = None
    phone: Optional[str] = None
    created_at: datetime
    
    model_config = ConfigDict(from_attributes=True)

# Student Schemas
class StudentBase(BaseModel):
    student_id: str = Field(..., description="Unique student identifier")
    first_name: str
    last_name: str
    email: Optional[str] = None
    phone: Optional[str] = None
    date_of_birth: Optional[datetime] = None
    address: Optional[str] = None
    graduation_date: Optional[datetime] = None

class StudentCreate(StudentBase):
    pass

class StudentUpdate(BaseModel):
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    date_of_birth: Optional[datetime] = None
    address: Optional[str] = None
    graduation_date: Optional[datetime] = None
    is_active: Optional[bool] = None

class StudentResponse(StudentBase):
    id: int
    enrollment_date: datetime
    is_active: bool
    created_at: datetime
    updated_at: Optional[datetime] = None
    
    model_config = ConfigDict(from_attributes=True)

# Teacher Schemas
class TeacherBase(BaseModel):
    teacher_id: str = Field(..., description="Unique teacher identifier")
    first_name: str
    last_name: str
    email: Optional[str] = None
    phone: Optional[str] = None
    subject: str
    department: Optional[str] = None
    salary: Optional[float] = None

class TeacherCreate(TeacherBase):
    pass

class TeacherUpdate(BaseModel):
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    subject: Optional[str] = None
    department: Optional[str] = None
    salary: Optional[float] = None
    is_active: Optional[bool] = None

class TeacherResponse(TeacherBase):
    id: int
    hire_date: Optional[datetime] = None
    is_foreigner: Optional[int] = Field(default=0, alias="isForeigner")
    is_active: bool
    created_at: datetime
    updated_at: Optional[datetime] = None

    # Additional fields needed for UI(relaxed types for safety)
    dob: Optional[Union[date, str]] = None
    gender: Optional[str] = None
    kName: Optional[str] = None
    eName: Optional[str] = None
    startWork: Optional[Union[date, str]] = None
    endWork: Optional[Union[date, str]] = None
    branch_name: Optional[str] = None
    nationality: Optional[str] = None
    religion: Optional[str] = None
    
    model_config = ConfigDict(from_attributes=True)

# Class Schemas
class ClassBase(BaseModel):
    class_code: str = Field(..., description="Unique class code")
    class_name: str
    subject: str
    description: Optional[str] = None
    credits: int = Field(default=3, ge=1, le=6)
    max_students: int = Field(default=30, ge=1, le=100)
    semester: str
    academic_year: str

class ClassCreate(ClassBase):
    teacher_id: int

class ClassUpdate(BaseModel):
    class_name: Optional[str] = None
    subject: Optional[str] = None
    description: Optional[str] = None
    credits: Optional[int] = Field(None, ge=1, le=6)
    max_students: Optional[int] = Field(None, ge=1, le=100)
    teacher_id: Optional[int] = None
    semester: Optional[str] = None
    academic_year: Optional[str] = None
    is_active: Optional[bool] = None

class ClassResponse(ClassBase):
    id: int
    teacher_id: int
    is_active: bool
    created_at: datetime
    updated_at: Optional[datetime] = None
    # Additional fields from joins
    branch_name: Optional[str] = None
    program_name: Optional[str] = None
    grade_name: Optional[str] = None
    grade_type_name: Optional[str] = None
    shift_name: Optional[str] = None
    academic_id: Optional[int] = None
    academic_us_name: Optional[str] = None
    
    model_config = ConfigDict(from_attributes=True, extra="allow")

class ClassWithTeacher(ClassResponse):
    teacher: TeacherResponse
    
    model_config = ConfigDict(from_attributes=True)

# Enrollment Schemas
class EnrollmentBase(BaseModel):
    student_id: int
    class_id: int
    grade: Optional[str] = Field(None, pattern="^[A-F]$")
    status: str = Field(default="enrolled", pattern="^(enrolled|completed|dropped)$")

class EnrollmentCreate(EnrollmentBase):
    pass

class EnrollmentUpdate(BaseModel):
    grade: Optional[str] = Field(None, pattern="^[A-F]$")
    status: Optional[str] = Field(None, pattern="^(enrolled|completed|dropped)$")

class EnrollmentResponse(EnrollmentBase):
    id: int
    enrollment_date: datetime
    created_at: datetime
    updated_at: Optional[datetime] = None
    
    model_config = ConfigDict(from_attributes=True)

class EnrollmentWithDetails(EnrollmentResponse):
    student: StudentResponse
    class_obj: ClassResponse
    
    model_config = ConfigDict(from_attributes=True)

# Response schemas with relationships
class StudentWithEnrollments(StudentResponse):
    enrollments: List[EnrollmentResponse] = []
    
    model_config = ConfigDict(from_attributes=True)

class TeacherClassSummary(BaseModel):
    id: int
    class_code: Optional[str] = Field(None, alias="classCode")
    class_name: Optional[str] = Field(None, alias="className")
    subject: Optional[str] = None
    teacher_id: Optional[int] = Field(None, alias="teacherId")
    semester: Optional[str] = None
    academic_year: Optional[str] = Field(None, alias="academicYear")
    is_active: Optional[bool] = Field(None, alias="isActive")
    branch_id: Optional[int] = Field(None, alias="branchId")
    branch_name: Optional[str] = Field(None, alias="branchName")
    program_id: Optional[int] = Field(None, alias="programId")
    program_name: Optional[str] = Field(None, alias="programName")
    program_short_code: Optional[str] = Field(None, alias="programShortCode")
    grade_id: Optional[int] = Field(None, alias="gradeId")
    grade_name: Optional[str] = Field(None, alias="gradeName")
    grade_type_name: Optional[str] = Field(None, alias="gradeTypeName")
    shift_id: Optional[int] = Field(None, alias="shiftId")
    shift: Optional[str] = None
    academic_id: Optional[int] = Field(None, alias="academicId") 
    academic_us_name: Optional[str] = Field(None, alias="academicUsName")
    student_count: Optional[int] = Field(0, alias="studentCount")

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

class TeacherWithClasses(TeacherResponse):
    classes: List[TeacherClassSummary] = []
    
    model_config = ConfigDict(from_attributes=True, extra="allow")

# Holiday Schemas
class HolidayBase(BaseModel):
    name: str
    date: date
    description: Optional[str] = None

class HolidayCreate(HolidayBase):
    pass

class HolidayUpdate(BaseModel):
    name: Optional[str] = None
    date: Optional[date] = None
    description: Optional[str] = None

class HolidayResponse(HolidayBase):
    id: int
    created_at: datetime
    updated_at: Optional[datetime] = None
    
    model_config = ConfigDict(from_attributes=True)


# Hot Event Schemas
class HotEventBase(BaseModel):
    title: Optional[str] = None
    message: str
    start_at: Optional[datetime] = None
    end_at: datetime
    audience: str = "all"
    event_type: str = "banner"
    frequency: str = "always"
    interval_minutes: Optional[int] = None
    max_impressions: Optional[int] = None
    link_url: Optional[str] = None
    status_text: Optional[str] = None
    is_active: bool = True



class HotEventCreate(HotEventBase):
    send_notification: bool = True


class HotEventUpdate(BaseModel):
    title: Optional[str] = None
    message: Optional[str] = None
    start_at: Optional[datetime] = None
    end_at: Optional[datetime] = None
    audience: Optional[str] = None
    event_type: Optional[str] = None
    frequency: Optional[str] = None
    interval_minutes: Optional[int] = None
    max_impressions: Optional[int] = None
    link_url: Optional[str] = None
    status_text: Optional[str] = None
    is_active: Optional[bool] = None
    send_notification: Optional[bool] = None


class HotEventResponse(HotEventBase):
    id: int
    created_by: Optional[int] = None
    created_at: datetime
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


# ============================================================
# MESSAGE SCHEMAS
# ============================================================

class MessageGroupMemberResponse(BaseModel):
    """Schema for group member response."""
    id: int
    group_id: int
    user_id: int
    user_type: Optional[str] = None  # 'teacher', 'parent', 'employee'
    role: str  # 'admin' or 'member'
    joined_at: datetime
    # Optional user details (joined from users table)
    user_name: Optional[str] = None
    user_k_name: Optional[str] = None
    user_e_name: Optional[str] = None
    user_image: Optional[str] = None
    
    model_config = ConfigDict(from_attributes=True)


class MessageGroupBase(BaseModel):
    """Base schema for message groups."""
    name: str = Field(..., max_length=255)
    type: str = Field(default="class")  # 'class' or 'custom'
    academic_year_id: Optional[int] = None
    grade_id: Optional[int] = None
    grade_type_id: Optional[int] = None
    program_id: Optional[int] = None
    branch_id: Optional[int] = None
    description: Optional[str] = None


class MessageGroupCreate(MessageGroupBase):
    """Schema for creating a message group."""
    created_by: int


class MessageGroupResponse(MessageGroupBase):
    """Schema for message group response."""
    id: int
    created_by: int
    created_at: datetime
    updated_at: Optional[datetime] = None
    member_count: Optional[int] = None  # Added dynamically
    unread_count: Optional[int] = None  # Added dynamically
    last_message: Optional[str] = None  # Added dynamically
    last_message_time: Optional[datetime] = None  # Added dynamically
    last_message_sender_image: Optional[str] = None # Added dynamically
    last_message_sender_name: Optional[str] = None # Added dynamically
    last_message_sender_gender: Optional[str] = None # Added dynamically
    program_name: Optional[str] = None  # For filtering
    branch_name: Optional[str] = None  # For filtering
    grade_type_name: Optional[str] = None  # For filtering
    group_image: Optional[str] = None  # Group cover photo
    
    model_config = ConfigDict(from_attributes=True)


class MessageBase(BaseModel):
    """Base schema for messages."""
    content: str
    message_type: str = Field(default="text")  # 'text', 'announcement', 'file'


class MessageCreate(MessageBase):
    """Schema for creating a message."""
    group_id: int
    sender_id: int
    send_notification: bool = True  # When True, send push to other members (like hot events)


class MessageResponse(MessageBase):
    """Schema for message response."""
    id: int
    group_id: int
    sender_id: int
    created_at: datetime
    read_by: Optional[str] = None  # JSON array of user IDs
    # Optional sender details (joined from users table)
    sender_name: Optional[str] = None
    sender_k_name: Optional[str] = None
    sender_e_name: Optional[str] = None
    sender_image: Optional[str] = None
    sender_gender: Optional[str] = None
    sender_type: Optional[str] = None
    pinned_by: Optional[int] = None
    pinned_at: Optional[datetime] = None
    is_hidden: int = 0
    
    model_config = ConfigDict(from_attributes=True)


class AutoCreateClassGroupsRequest(BaseModel):
    """Request schema for auto-creating class groups."""
    academic_year_id: Optional[int] = None  # If None, uses current active year


# ==================== Group Admin Management Schemas ====================

class AddMemberRequest(BaseModel):
    """Request schema for adding a member to a group."""
    user_id: int
    user_type: str  # 'teacher', 'parent', 'student', 'employee'
    role: str = Field(default="member")  # 'admin' or 'member'


class RemoveMemberRequest(BaseModel):
    """Request schema for removing a member from a group."""
    member_id: int


class BanUserRequest(BaseModel):
    """Request schema for banning a user from a group."""
    user_id: int
    user_type: str  # 'teacher', 'parent', 'student', 'employee'
    reason: Optional[str] = None
    expires_at: Optional[datetime] = None  # NULL = permanent ban


class BanResponse(BaseModel):
    """Response schema for ban operations."""
    id: int
    group_id: int
    user_id: int
    user_type: str
    banned_by: int
    reason: Optional[str]
    banned_at: datetime
    expires_at: Optional[datetime]
    is_active: bool
    # Optional user details
    user_name: Optional[str] = None
    user_k_name: Optional[str] = None
    user_e_name: Optional[str] = None
    
    model_config = ConfigDict(from_attributes=True)


class GroupSettingsResponse(BaseModel):
    """Response schema for group settings."""
    id: int
    group_id: int
    can_send_text: bool
    can_send_files: bool
    can_send_images: bool
    can_send_voice: bool
    only_admins_can_post: bool
    created_at: datetime
    updated_at: datetime
    
    model_config = ConfigDict(from_attributes=True)


class UpdateSettingsRequest(BaseModel):
    """Request schema for updating group settings."""
    can_send_text: Optional[bool] = None
    can_send_files: Optional[bool] = None
    can_send_images: Optional[bool] = None
    can_send_voice: Optional[bool] = None
    only_admins_can_post: Optional[bool] = None


class DeleteMessageRequest(BaseModel):
    """Request schema for deleting a message."""
    message_id: int


class HideMessageRequest(BaseModel):
    """Request schema for hiding/unhiding a message."""
    message_id: int
    is_hidden: bool
