"""Add partner_images table

Revision ID: 3da87776798d
Revises: 24de52abf50d
Create Date: 2026-02-26 15:16:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3da87776798d'
down_revision = '24de52abf50d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_images_id'), 'partner_images', ['id'], unique=False)
    op.create_index(op.f('ix_partner_images_partner_id'), 'partner_images', ['partner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_images_partner_id'), table_name='partner_images')
    op.drop_index(op.f('ix_partner_images_id'), table_name='partner_images')
    op.drop_table('partner_images')
    # ### end Alembic commands ###
